
# env
# If you need envs in your app, set enabled 'true',
# and set you envs like name1, name2 as ordinary envs used in your app.
env:
  enabled: false
  values:
    - name: name1
      value: value1
    - name: name2
      value: value2

# volume
# configs to mount configuration files in your app.
# host-time to mount host time.
volume:
  # If you set enabled true, you must replace the value of configMap name 'ConfigmapName' by your app name when deploying,
  # otherwise you will not deploy your app successfully.
  # But you will also succeed by modifying the configMap name using deployment name.
  enabled: false
  # sef configMapEnabled 'true' if the configMap in volumes is set.
  # the configMap in volumes named 'host-time' must be set to mount host time.
  configMapEnabled: false
  volumes:
    - name: configs
      configMap:
        # This is an initial value 'ConfigmapName',
        # it must be modified.
        name: ConfigmapName
    - name: host-time
      hostPath:
        path: /etc/localtime
        type: ''
  volumeMounts:
    - name: configs
      # This is an initial value '/config',
      # it must be modified to your mount path.
      mountPath: /config
    - name: host-time
      mountPath: /etc/localtime
